AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: bitsa - API Gateway + Lambda + Tikkl Signature Authorizer

Globals:
  Function:
    Timeout: 500
    Runtime: python3.12
    Architectures:
      - x86_64
    MemorySize: 256

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
      - stg
      - qa
    Description: Deployment stage (dev, stg, qa, or prod)

  LambdaRoleArn:
    Type: String
    Default: arn:aws:iam::785000992152:role/BitsaRole
    Description: IAM Role ARN for Lambda execution

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "bits-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET, POST, PUT, DELETE, OPTIONS'"
        AllowHeaders: "'AUTHORIZATION, Content-Type, X-Amz-Date, X-Api-Key, X-Amz-Security-Token, X-Amz-User-Agent, X-Tikkl-Signature'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          TikklSignatureAuthorizer:
            FunctionArn: !GetAtt TikklSignatureAuthorizer.Arn
            Identity:
              Headers:
                - X-Tikkl-Signature

  TikklSignatureAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "tikkl-authorizer"
      Handler: lambda.authorizer.lambda_handler
      Role: !Ref LambdaRoleArn
      Environment:
        Variables:
          TIKKL_SECRET: "Di47eNI06-d410BF-85I4t9D6424m0sz3h1LmPVv5W8"
          TZ: Asia/Kolkata
          STAGE: !Ref Stage
      Policies:
        - AWSLambdaBasicExecutionRole

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "bits-app-user"
      Handler: lambda.app.lambda_handler
      Role: !Ref LambdaRoleArn
      Environment:
        Variables:
          TZ: Asia/Kolkata
          STAGE: !Ref Stage
          EXPECTED_API_KEY: "aB3!k9Lm@zR5qX7wP2eT8vY4dF6#rT1$gH5^VcL9mNpQ2rT8uLz#qW3eXpL9tR6yEwD2mX8qZsT8$mQ#vLp9ZdE7rT2yU5iO0jH7*qN3pVzL9tR6yEwD2mX8q"
          X_Tikkl_Signature: "24615c67ca5ad67e10a883a1100d79ebbe75024d1321ec4dcbdad9d668f682b0"
      Events:
        CreateRegistration:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /registration
            Method: POST
        BitsaaApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY


  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "bits-app-email"
      Handler: lambda.email.lambda_handler
      Role: !Ref LambdaRoleArn
      Environment:
        Variables:
          TZ: Asia/Kolkata
          IMAP_SERVER: "mail.uskcorp.in"
          IMAP_PORT: "993"
          EMAIL_USER: "hr@uskcorp.in"
          EMAIL_PASSWORD: "Infosys@123"

  CloudWatchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "CloudWatchLogsPolicy"
      Roles:
        - BitsaRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"

Outputs:
  UserFunctionApi:
    Description: "API Gateway endpoint URL for ${Stage} stage"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"

  UserFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
